proposicoes = {
  1: "O inglês mora na casa vermelha.",
  2: "O sueco tem cachorros.",
  3: "O dinamarquês bebe chá.",
  4: "A casa verde fica à esquerda da casa branca.",
  5: "O morador da casa verde bebe café.",
  6: "A pessoa que fuma Pall Mall cria pássaros.",
  7: "O morador da casa amarela fuma Dunhill.",
  8: "O morador da casa central bebe leite.",
  9: "O norueguês mora na primeira casa.",
  10: "O homem que fuma Blends mora ao lado do que tem gatos.",
  11: "O homem que cria cavalos mora ao lado do que fuma Dunhill.",
  12: "O homem que fuma Bluemaster bebe cerveja.",
  13: "O alemão fuma Prince.",
  14: "O norueguês vive ao lado da casa azul.",
  15: "O homem que fuma Blends é vizinho do que bebe água.",
}